#!/usr/bin/env bash
# ---------------------------------------------------------------------------- #
#  Venus OS Addon – Initialisation Script                                       #
#  Called once at container start by the s6-overlay "init-addon" oneshot.      #
#  Reads HA options from /data/options.json and writes runtime config files.   #
# ---------------------------------------------------------------------------- #
set -euo pipefail

# ── bashio helpers ─────────────────────────────────────────────────────────────
# bashio is provided by the HA base image.  Fall back to thin stubs so this
# script can be tested outside of a full HA environment.
if [ -f /usr/lib/bashio/bashio.sh ]; then
    # shellcheck source=/dev/null
    . /usr/lib/bashio/bashio.sh
else
    bashio::log.info()    { echo "[INFO]  $*";  }
    bashio::log.warning() { echo "[WARN]  $*";  }
    bashio::log.error()   { echo "[ERROR] $*";  }
    bashio::config() {
        local key="$1"
        jq -r ".\"${key}\" // empty" /data/options.json 2>/dev/null || echo ""
    }
    bashio::config.true() {
        local val
        val=$(jq -r ".\"$1\"" /data/options.json 2>/dev/null)
        [ "${val}" = "true" ]
    }
fi

bashio::log.info "Starting Venus OS addon initialisation..."

# ── Directory setup ───────────────────────────────────────────────────────────
mkdir -p /run/dbus
mkdir -p /data/mosquitto/db
mkdir -p /data/venus
mkdir -p /data/conf
mkdir -p /etc/venus
mkdir -p /etc/dbus-mqtt
mkdir -p /var/log/venus

# ── VRM Portal ID ─────────────────────────────────────────────────────────────
# Venus daemons (especially dbus-mqtt) use a portal ID to namespace MQTT topics
# as  N/<portalid>/#  matching the real Venus OS / VRM Portal convention.
VRM_ID="$(bashio::config 'vrm_id')"
if [ -z "${VRM_ID}" ]; then
    if [ ! -f /data/venus/unique-id ]; then
        # Generate a stable 12-char hex ID, persisted across restarts.
        tr -dc 'a-f0-9' < /dev/urandom 2>/dev/null | head -c 12 \
            > /data/venus/unique-id \
            || printf '%s' "$(cat /proc/sys/kernel/random/uuid | tr -d '-' | cut -c1-12)" \
                > /data/venus/unique-id
    fi
    VRM_ID="$(cat /data/venus/unique-id)"
else
    printf '%s' "${VRM_ID}" > /data/venus/unique-id
fi

# Standard path that Venus daemons look for.
ln -sf /data/venus/unique-id /etc/venus/unique-id
bashio::log.info "VRM Portal ID: ${VRM_ID}"

# ── Mosquitto configuration ───────────────────────────────────────────────────
MQTT_USERNAME="$(bashio::config 'mqtt_username')"
MQTT_PASSWORD="$(bashio::config 'mqtt_password')"

{
    echo "# Generated by Venus OS addon run.sh — do not edit manually."
    echo "listener 1883"
    echo "persistence true"
    echo "persistence_location /data/mosquitto/db/"
    echo "log_dest stdout"
    echo "log_type error"
    echo "log_type warning"
    echo "log_type notice"
    echo "log_type information"
} > /data/mosquitto/mosquitto.conf

if [ -n "${MQTT_USERNAME}" ]; then
    {
        echo "allow_anonymous false"
        echo "password_file /data/mosquitto/passwd"
    } >> /data/mosquitto/mosquitto.conf
    mosquitto_passwd -b -c /data/mosquitto/passwd \
        "${MQTT_USERNAME}" "${MQTT_PASSWORD}"
    bashio::log.info "MQTT authentication enabled for user: ${MQTT_USERNAME}"
else
    echo "allow_anonymous true" >> /data/mosquitto/mosquitto.conf
    bashio::log.warning \
        "MQTT is running WITHOUT authentication. Set mqtt_username/mqtt_password to secure the broker."
fi

# ── dbus-mqtt configuration ───────────────────────────────────────────────────
# dbus-mqtt reads /etc/dbus-mqtt/config.ini for broker and VRM settings.
{
    echo "# Generated by Venus OS addon run.sh"
    echo "[DEFAULT]"
    echo "MqttBroker = localhost"
    echo "MqttPort = 1883"
    echo "VrmBrokerId = ${VRM_ID}"
} > /etc/dbus-mqtt/config.ini

if [ -n "${MQTT_USERNAME}" ]; then
    {
        echo "MqttUsername = ${MQTT_USERNAME}"
        echo "MqttPassword = ${MQTT_PASSWORD}"
    } >> /etc/dbus-mqtt/config.ini
fi

VRM_TOKEN="$(bashio::config 'vrm_token')"
if [ -n "${VRM_TOKEN}" ]; then
    {
        echo ""
        echo "[VrmApi]"
        echo "Token = ${VRM_TOKEN}"
    } >> /etc/dbus-mqtt/config.ini
    bashio::log.info "VRM Portal token configured for cloud connectivity."
fi

# ── VE.Direct serial interface ────────────────────────────────────────────────
VEDIRECT_PORT="$(bashio::config 'vedirect_port')"
if [ -n "${VEDIRECT_PORT}" ]; then
    VEDIRECT_BAUD="$(bashio::config 'vedirect_baud')"
    VEDIRECT_BAUD="${VEDIRECT_BAUD:-19200}"
    bashio::log.info "VE.Direct: ${VEDIRECT_PORT} @ ${VEDIRECT_BAUD} baud"
    printf '%s' "${VEDIRECT_PORT}" > /data/venus/vedirect_port
    printf '%s' "${VEDIRECT_BAUD}" > /data/venus/vedirect_baud
else
    rm -f /data/venus/vedirect_port /data/venus/vedirect_baud
    bashio::log.info "No VE.Direct port configured (set the vedirect_port option to enable)."
fi

# ── VE.Can / CAN bus interface ────────────────────────────────────────────────
VECAN_IFACE="$(bashio::config 'vecan_interface')"
if [ -n "${VECAN_IFACE}" ]; then
    bashio::log.info "Configuring VE.Can interface: ${VECAN_IFACE}"
    if ip link show "${VECAN_IFACE}" > /dev/null 2>&1; then
        ip link set "${VECAN_IFACE}" down            2>/dev/null || true
        ip link set "${VECAN_IFACE}" up type can bitrate 250000 2>/dev/null || true
        ip link set "${VECAN_IFACE}" up              2>/dev/null || true
        bashio::log.info "VE.Can interface ${VECAN_IFACE} brought up at 250 kbps."
    else
        bashio::log.warning \
            "CAN interface '${VECAN_IFACE}' not found. Ensure the kernel CAN module is loaded on the HA host (e.g. mcp251x, gs_usb)."
    fi
else
    bashio::log.info "No VE.Can interface configured (set the vecan_interface option to enable)."
fi

# ── Modbus TCP (optional) ─────────────────────────────────────────────────────
if bashio::config.true 'modbus_enabled'; then
    touch /data/venus/modbus_enabled
    bashio::log.info "Modbus TCP server will start on port 502."
else
    rm -f /data/venus/modbus_enabled
fi

bashio::log.info "Venus OS addon initialisation complete."
